import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Task, Partner, Customer, User, OnboardingStage } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

interface TaskManagerReturn {
  tasks: Task[];
  loading: boolean;
  createTask: (task: Omit<Task, 'id' | 'createdAt'>) => Promise<void>;
  updateTask: (taskId: string, updates: Partial<Task>) => Promise<void>;
  deleteTask: (taskId: string) => Promise<void>;
  getOnboardingTasks: (partnerId: string, stage?: string) => Task[];
  markTaskComplete: (taskId: string) => Promise<void>;
  refreshTasks: () => Promise<void>;
}

export const useTaskManager = (): TaskManagerReturn => {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  const fetchTasks = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('tasks')
        .select(`
          *,
          partner:partners!partner_id(name, company),
          assigned_user:profiles!tasks_assigned_to_fkey(first_name, last_name),
          created_user:profiles!tasks_assigned_by_fkey(first_name, last_name)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;

      // Transform database format to frontend format
      const transformedTasks: Task[] = data?.map(task => ({
        id: task.id,
        title: task.title,
        description: task.description,
        status: task.status as Task['status'],
        priority: task.priority as Task['priority'],
        type: task.type as Task['type'],
        assignedTo: task.assigned_to,
        assignedBy: task.assigned_by,
        customerId: task.portal_customer_id,
        customerDomain: task.customer_domain,
        partnerId: task.partner_id,
        portal_reseller_id: task.portal_reseller_id,
        dueDate: task.due_date ? new Date(task.due_date) : undefined,
        createdAt: new Date(task.created_at),
        updatedAt: task.updated_at ? new Date(task.updated_at) : undefined,
        completedAt: task.completed_at ? new Date(task.completed_at) : undefined,
        notes: task.notes,
        tags: task.tags || [],
        estimatedHours: task.estimated_hours,
        actualHours: task.actual_hours,
        isOnboardingTask: task.is_onboarding_task,
        onboardingStage: task.onboarding_stage as OnboardingStage,
        stageRequirement: task.stage_requirement,
        autoGenerated: task.auto_generated,
      })) || [];

      setTasks(transformedTasks);
    } catch (error) {
      console.error('Error fetching tasks:', error);
      toast.error('Failed to load tasks');
    } finally {
      setLoading(false);
    }
  };

  const createTask = async (taskData: Omit<Task, 'id' | 'createdAt'>) => {
    try {
      const { data, error } = await supabase
        .from('tasks')
        .insert({
          title: taskData.title,
          description: taskData.description,
          status: taskData.status,
          priority: taskData.priority,
          type: taskData.type,
          assigned_to: taskData.assignedTo,
          assigned_by: user?.id,
          customer_id: taskData.customerId,
          partner_id: taskData.partnerId,
          due_date: taskData.dueDate?.toISOString(),
          notes: taskData.notes,
          tags: taskData.tags,
          estimated_hours: taskData.estimatedHours,
          actual_hours: taskData.actualHours,
          is_onboarding_task: taskData.isOnboardingTask || false,
          onboarding_stage: taskData.onboardingStage,
          stage_requirement: taskData.stageRequirement || false,
          auto_generated: taskData.autoGenerated || false,
        })
        .select()
        .single();

      if (error) throw error;

      toast.success('Task created successfully');
      await fetchTasks();
    } catch (error) {
      console.error('Error creating task:', error);
      toast.error('Failed to create task');
    }
  };

  const updateTask = async (taskId: string, updates: Partial<Task>) => {
    try {
      const updateData: any = {};
      
      if (updates.title !== undefined) updateData.title = updates.title;
      if (updates.description !== undefined) updateData.description = updates.description;
      if (updates.status !== undefined) updateData.status = updates.status;
      if (updates.priority !== undefined) updateData.priority = updates.priority;
      if (updates.type !== undefined) updateData.type = updates.type;
      if (updates.assignedTo !== undefined) updateData.assigned_to = updates.assignedTo;
      if (updates.customerId !== undefined) updateData.customer_id = updates.customerId;
      if (updates.partnerId !== undefined) updateData.partner_id = updates.partnerId;
      if (updates.dueDate !== undefined) updateData.due_date = updates.dueDate?.toISOString();
      if (updates.notes !== undefined) updateData.notes = updates.notes;
      if (updates.tags !== undefined) updateData.tags = updates.tags;
      if (updates.estimatedHours !== undefined) updateData.estimated_hours = updates.estimatedHours;
      if (updates.actualHours !== undefined) updateData.actual_hours = updates.actualHours;
      if (updates.completedAt !== undefined) updateData.completed_at = updates.completedAt?.toISOString();

      const { error } = await supabase
        .from('tasks')
        .update(updateData)
        .eq('id', taskId);

      if (error) throw error;

      toast.success('Task updated successfully');
      await fetchTasks();
    } catch (error) {
      console.error('Error updating task:', error);
      toast.error('Failed to update task');
    }
  };

  const deleteTask = async (taskId: string) => {
    try {
      const { error } = await supabase
        .from('tasks')
        .delete()
        .eq('id', taskId);

      if (error) throw error;

      toast.success('Task deleted successfully');
      await fetchTasks();
    } catch (error) {
      console.error('Error deleting task:', error);
      toast.error('Failed to delete task');
    }
  };

  const markTaskComplete = async (taskId: string) => {
    await updateTask(taskId, {
      status: 'completed',
      completedAt: new Date(),
    });
  };

  const getOnboardingTasks = (partnerId: string, stage?: string) => {
    return tasks.filter(task => 
      task.isOnboardingTask && 
      task.partnerId === partnerId &&
      (!stage || task.onboardingStage === stage)
    );
  };

  const refreshTasks = async () => {
    await fetchTasks();
  };

  useEffect(() => {
    fetchTasks();

    // Set up real-time subscription
    const channel = supabase
      .channel('tasks-changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'tasks'
        },
        () => {
          fetchTasks();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user]);

  return {
    tasks,
    loading,
    createTask,
    updateTask,
    deleteTask,
    getOnboardingTasks,
    markTaskComplete,
    refreshTasks,
  };
};