// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzfrqjrqdlsvqbejsbmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZnJxanJxZGxzdnFiZWpzYm11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDIzOTQsImV4cCI6MjA2NzYxODM5NH0.o7ioYBWpEj9VCu6EEPuFLBq4d2Rwjmx_oEqRAQtzP_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // It's generally recommended to use the default browser storage (localStorage)
    // unless you have a specific reason to override it.
  },
});