import { Customer, Partner, Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'JumpCloud',
    website: 'jumpcloud.com',
    category: 'Identity Management',
    description: 'Cloud-based directory service and identity management platform',
    status: 'active',
    customersCount: 8,
    plans: [
      {
        id: '1-1',
        name: 'Core',
        price: 2.50,
        billing: 'monthly',
      },
      {
        id: '1-2',
        name: 'Business',
        price: 8.00,
        renewalPrice: 9.50,
        billing: 'monthly',
        isPopular: true,
      },
      {
        id: '1-3',
        name: 'Enterprise',
        price: 20.00,
        billing: 'monthly',
      }
    ],
    price: 299.99,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Scalefusion',
    website: 'scalefusion.com',
    category: 'Mobile Device Management',
    description: 'Unified endpoint management and mobile device management solution',
    status: 'active',
    customersCount: 5,
    plans: [
      {
        id: '2-1',
        name: 'Growth',
        price: 2.00,
        billing: 'monthly',
      },
      {
        id: '2-2',
        name: 'Business',
        price: 4.00,
        billing: 'monthly',
        isPopular: true,
      },
      {
        id: '2-3',
        name: 'Enterprise',
        price: 7.00,
        billing: 'monthly',
      }
    ],
    price: 199.99,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Google Workspace',
    website: 'workspace.google.com',
    category: 'Productivity Suite',
    description: 'Cloud-based productivity and collaboration tools',
    status: 'active',
    customersCount: 12,
    plans: [
      {
        id: '3-1',
        name: 'Business Starter',
        price: 6.00,
        billing: 'monthly',
      },
      {
        id: '3-2',
        name: 'Business Standard',
        price: 12.00,
        billing: 'monthly',
        isPopular: true,
      },
      {
        id: '3-3',
        name: 'Business Plus',
        price: 18.00,
        billing: 'monthly',
      }
    ],
    price: 149.99,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Microsoft 365',
    website: 'microsoft.com/microsoft-365',
    category: 'Productivity Suite',
    description: 'Integrated cloud-based productivity and business applications',
    status: 'active',
    customersCount: 15,
    plans: [
      {
        id: '4-1',
        name: 'Business Basic',
        price: 6.00,
        billing: 'monthly',
      },
      {
        id: '4-2',
        name: 'Business Standard',
        price: 12.50,
        billing: 'monthly',
        isPopular: true,
      },
      {
        id: '4-3',
        name: 'Business Premium',
        price: 22.00,
        billing: 'monthly',
      }
    ],
    price: 179.99,
    createdAt: new Date('2024-02-15'),
  },
  
];

export const mockPartners: Partner[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@techsolutions.com',
    company: 'Tech Solutions Inc',
    specialization: 'Enterprise Software',
    identity: 'system-integrator',
    customersCount: 15,
    newRevenue: 150000,
    renewalRevenue: 100000,
    totalValue: 250000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-10'),
    productTypes: ['Identity Management', 'Productivity Suite'],
    paymentTerms: 'net-30',
    assignedUserIds: ['2', '5', '6'],
    zone: 'north',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@digitalcorp.com',
    company: 'Digital Corp',
    specialization: 'Digital Marketing',
    identity: 'digital-marketer',
    customersCount: 12,
    newRevenue: 110000,
    renewalRevenue: 70000,
    totalValue: 180000,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-28'),
    productTypes: ['Communication', 'Mobile Device Management'],
    paymentTerms: 'net-60',
    assignedUserIds: ['3', '7'],
    zone: 'east',
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@innovate.com',
    company: 'Innovate LLC',
    specialization: 'Cloud Services',
    identity: 'web-app-developer',
    customersCount: 8,
    newRevenue: 120000,
    renewalRevenue: 0,
    totalValue: 120000,
    status: 'active',
    createdAt: new Date('2024-03-10'),
    agreementSigned: false,
    productTypes: ['Productivity Suite', 'Identity Management'],
    paymentTerms: 'monthly',
    assignedUserIds: ['4', '5'],
    zone: 'west',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Alice Wilson',
    email: 'alice@example.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Corp',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '3', '4'],
    assignedUserIds: ['2', '6'],
    createdAt: new Date('2024-04-01'),
    value: 25000,
    zone: 'north',
  },
  {
    id: '2',
    name: 'Bob Martinez',
    email: 'bob@startup.io',
    phone: '+1 (555) 234-5678',
    company: 'Startup Inc',
    status: 'pending',
    partnerId: '2',
    productIds: ['2', '6'],
    assignedUserIds: ['3', '7', '5'],
    createdAt: new Date('2024-05-15'),
    value: 15000,
    zone: 'south',
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol@enterprise.com',
    phone: '+1 (555) 345-6789',
    company: 'Enterprise Ltd',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '4', '5'],
    assignedUserIds: ['2', '6'],
    createdAt: new Date('2024-05-20'),
    value: 45000,
    zone: 'east',
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@tech.com',
    phone: '+1 (555) 456-7890',
    company: 'Tech Innovations',
    status: 'inactive',
    partnerId: '3',
    productIds: ['3', '6'],
    assignedUserIds: ['4'],
    createdAt: new Date('2024-06-01'),
    value: 8000,
    zone: 'west',
  },
];
